import type { AgentSkillSummary } from "@/services/api/canvas-agent";

type SkillDisplay = Pick<AgentSkillSummary, "name" | "description" | "shortDescription" | "interface">;

// 这里只负责技能库的本地展示；技能文件本身仍保留原始内容，避免改变 Codex 的执行语义。
const chineseTitles: Record<string, string> = {
    "frontend-design": "前端界面设计",
    "vercel-react-best-practices": "Vercel React 最佳实践",
    "Batch edit photos": "批量编辑照片",
    "Create mockups": "创建产品样机",
    "Create social variations": "生成社交媒体尺寸版本",
    "Design from template": "从模板创建设计",
    "Edit quick cut": "快速剪辑",
    "Retouch portraits": "人像修饰",
    "Frontend App Builder": "前端应用构建",
    "Frontend Testing Debugging": "前端测试与调试",
    "React Best Practices": "React 最佳实践",
    "shadcn/ui": "shadcn/ui 组件实践",
    "Stripe Best Practices": "Stripe 最佳实践",
    "Supabase Postgres Best Practices": "Supabase Postgres 最佳实践",
    "Volcengine Supabase (AI-native BaaS)": "火山引擎 Supabase（AI 原生 BaaS）",
    "Deep Research": "深度调研",
    "Documents": "文档处理",
    "Douyin Video Replication": "抖音视频复刻",
    "GSAP": "GSAP 动画",
    "HyperFrames": "HyperFrames 视频合成",
    "HyperFrames CLI": "HyperFrames 命令行",
    "HyperFrames Registry": "HyperFrames 组件库",
    "Website to HyperFrames": "网站转 HyperFrames 视频",
    "Analytics Dashboard": "数据分析仪表盘",
    "Business Review": "业务复盘",
    "Design Report": "设计报告",
    "Experiment Analysis": "实验分析",
    "Financial Budget": "财务预算",
    "Investment Committee Memo": "投委会备忘录",
    "Legal Memorandum": "法律备忘录",
    "Market Trends Report": "市场趋势报告",
    "Minimal Letterhead": "极简信笺模板",
    "Operating Calendar": "运营日历",
    "Operating Review": "运营复盘",
    "Project Kickoff": "项目启动",
    "Project Tracker": "项目跟踪",
    "Sales Pipeline": "销售管道",
    "Simple Dark Mode": "简洁深色模式",
    "Simple Light Mode": "简洁浅色模式",
    "Strategy Memorandum": "战略备忘录",
    "System Design": "系统设计",
    "Team Alignment": "团队对齐",
    "Three-Statement Forecast": "三表预测",
    "PDF": "PDF 处理",
    "Presentations": "演示文稿",
    "Audit": "产品体验审查",
    "Design QA": "设计质量检查",
    "Get Context": "获取设计上下文",
    "Ideate": "设计构思",
    "Image To Code": "图片转代码",
    "Product Design": "产品设计",
    "Research": "产品调研",
    "Share": "分享设计",
    "URL To Code": "网址转代码",
    "User Context": "用户上下文",
    "Spreadsheets": "电子表格",
    "Excel Live Control": "Excel 实时控制",
    "Template Creator": "模板创建器",
    "Visualize": "可视化",
    "Image Gen": "图像生成",
    "OpenAI Docs": "OpenAI 文档",
    "Plugin Creator": "插件创建器",
    "Review Agent": "代码审查助手",
    "Skill Creator": "技能创建器",
    "Skill Installer": "技能安装器",
    "MiniMax H3 Prompt Writing": "MiniMax H3 提示词编写",
    "GPT Image 2 Skill": "GPT Image 2 图像生成",
    "kimi-webbridge": "Kimi 浏览器桥接",
    "plugin-management:plugin-management": "插件管理",
    "infinite-canvas:canvas": "无限画布操作",
    "infinite-canvas:open-canvas": "打开无限画布",
    "sites:sites-building": "网站构建",
    "sites:sites-hosting": "网站托管",
    "/remotion-best-practices": "Remotion 最佳实践",
    "/remotion-captions": "Remotion 字幕",
    "/remotion-create": "创建 Remotion 视频",
    "/remotion-docs": "Remotion 文档",
    "/remotion-interactivity": "Remotion 交互",
    "/remotion-maps": "Remotion 地图",
    "/remotion-markup": "Remotion 标记",
    "/remotion-multimedia": "Remotion 多媒体",
    "/remotion-render": "渲染 Remotion 视频",
    "/remotion-saas": "Remotion SaaS 应用",
    "/remotion-studio": "Remotion Studio",
    "/remotion-upgrade": "升级 Remotion",
    "arkcli-agent": "ArkCLI 托管智能体",
    "arkcli-api-explorer": "ArkCLI API 浏览器",
    "arkcli-auth": "ArkCLI 认证管理",
    "arkcli-billing": "ArkCLI 账单查询",
    "arkcli-chat": "ArkCLI 对话",
    "arkcli-code-example": "ArkCLI 代码示例",
    "arkcli-config": "ArkCLI 配置管理",
    "arkcli-connect": "ArkCLI 连接管理",
    "arkcli-custommodel": "ArkCLI 自定义模型",
    "arkcli-deploy": "ArkCLI 部署接入点",
    "arkcli-doctor": "ArkCLI 故障诊断",
    "arkcli-gen": "ArkCLI 图像与视频生成",
    "arkcli-helper": "ArkCLI 助手配置",
    "arkcli-infer-endpoint": "ArkCLI 推理接入点",
    "arkcli-models": "ArkCLI 模型查询",
    "arkcli-onboard": "ArkCLI 接入向导",
    "arkcli-plans": "ArkCLI 套餐管理",
    "arkcli-pricing": "ArkCLI 定价查询",
    "arkcli-profile": "ArkCLI 配置档案",
    "arkcli-resources": "ArkCLI 资源查询",
    "arkcli-shared": "ArkCLI 共享执行协议",
    "arkcli-train-finetune": "ArkCLI 模型微调",
    "arkcli-understand": "ArkCLI 多模态理解",
    "arkcli-usage": "ArkCLI 用量查询",
    "canva:canva-brand-check": "Canva 品牌规范检查",
    "canva:canva-branded-presentation": "Canva 品牌演示文稿",
    "canva:canva-bulk-create": "Canva 批量创建",
    "canva:canva-design-feedback": "Canva 设计反馈",
    "canva:canva-edit-design": "Canva 编辑设计",
    "canva:canva-implement-feedback": "Canva 落地设计反馈",
    "canva:canva-resize-for-social-media": "Canva 社交媒体尺寸调整",
    "canva:canva-translate-design": "Canva 设计翻译",
    "figma:figma-code-connect": "Figma 代码连接",
    "figma:figma-create-new-file": "Figma 新建文件",
    "figma:figma-design-to-code": "Figma 设计转代码",
    "figma:figma-generate-design": "Figma 生成设计",
    "figma:figma-generate-diagram": "Figma 生成图表",
    "figma:figma-generate-library": "Figma 生成组件库",
    "figma:figma-implement-motion": "Figma 动效实现",
    "figma:figma-swiftui": "Figma 与 SwiftUI",
    "figma:figma-use": "使用 Figma",
    "figma:figma-use-figjam": "使用 Figma FigJam",
    "figma:figma-use-motion": "使用 Figma 动效",
    "figma:figma-use-slides": "使用 Figma 幻灯片",
};

const hasChinese = (value: string) => /[\u3400-\u9fff]/.test(value);

export function localizeSkillDisplay(skill: SkillDisplay) {
    const originalTitle = skill.interface?.displayName || skill.name;
    const originalDescription = skill.interface?.shortDescription || skill.shortDescription || skill.description || "";
    const title = chineseTitles[originalTitle] || (hasChinese(originalTitle) ? originalTitle : "本机技能");
    const description = hasChinese(originalDescription)
        ? originalDescription
        : `${title}相关的本机 Codex 工作流程与使用说明。点击“查看内容”可阅读原始 SKILL.md。`;

    return { title, description };
}
